exclude: '(\.git|\.mypy_cache|\.pytest_cache|\.tox|\.venv|venv|.env|env|\.envs|\.vscode|static|media/|.*/templates|.*/migrations|.*/grpc|__init__.py)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ '--line-length=120' ]
  #- repo: https://github.com/asottile/reorder_python_imports
  #  rev: v3.8.2
  #  hooks:
  #  -   id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args: [ '--max-line-length=120' ]
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Run type checks
        args: [
          "--ignore-missing-imports",
          "--install-types",
          "--non-interactive",
          "--check-untyped-defs"
        ]
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: python src/manage.py makemigrations --check --dry-run
        types: [ "python" ]
        pass_filenames: false
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ '--profile', 'black' ]
  - repo: local
    hooks:
      - id: django-test
        language: system
        name: django-test
        entry: python src/manage.py test --parallel --exclude-tag=dev-mode
        always_run: true
        types: [ "python" ]
        pass_filenames: false
