version: '3.9'

services:

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: slab_web
    networks:
      - shared_network
    command: >
      /bin/sh -c "while ! nc -z redis 6379; do sleep 1; done;
                  while ! nc -z postgres 5432; do sleep 1; done;
                  python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn --workers ${WORKERS_COUNT:-4} --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./../src:/app/src
      - ./../static:/app/static
      - ./../media:/app/media
      - ./../logs:/app/logs
      - ./../assets:/app/assets
    ports:
      - "8000:8000"
    env_file:
      - ./../.envs/.env
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER=redis://redis:6379/0

  
  postgres:
    image: postgres:17.0
    container_name: slab_db
    env_file:
      - ./../.envs/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"

    networks:
      - shared_network

  redis:
    image: redis:7.2-alpine
    container_name: slab_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.volumes/redis_data:/data

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: slab_celery
    networks:
      - shared_network
    command: celery -A config worker --loglevel=INFO --concurrency=${CELERY_WORKERS}
    volumes:
      - ./../src:/app/src
      - ./../media:/app/media
      - ./../logs:/app/logs
    depends_on:
      - redis
      - web
    env_file:
      - ./../.envs/.env

networks:
  shared_network:
    driver: bridge
