version: '3.9'

services:

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: template_web
    networks:
      - shared_network
    command: >
      /bin/sh -c "while ! nc -z redis 6379; do sleep 1; done;
                  while ! nc -z postgres 5432; do sleep 1; done;
                  python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn --workers ${WORKERS_COUNT:-4} --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./../src:/app/src
      - ./../static:/app/static
      - ./../media:/app/media
      - ./../logs:/app/logs
      - ./../assets:/app/assets
    ports:
      - "8080:8000"
    env_file:
      - ./../.envs/.env
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER=redis://redis:6379/0


  postgres:
    image: postgres:17.0
    container_name: template_db
    env_file:
      - ./../.envs/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"

    networks:
      - shared_network

  redis:
    image: redis:7.2-alpine
    container_name: template_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.volumes/redis_data:/data

  rabbit:
    image: rabbitmq:4.0-management
    container_name: template_rabbit
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15682:15672"
    networks:
      - shared_network
    volumes:
      - ./.volumes/rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - postgres
    env_file:
      - ./../.envs/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: template_celery
    networks:
      - shared_network
    command: celery -A config worker --loglevel=INFO --concurrency=${CELERY_WORKERS:-2}
    volumes:
      - ./../src:/app/src
      - ./../media:/app/media
      - ./../logs:/app/logs
    depends_on:
      - redis
    env_file:
      - ./../.envs/.env

networks:
  shared_network:
    driver: bridge
